version: "3"
services:
  analytics-consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile-analytics
    networks:
      - wikiflow-network
    ports:
      - "4040:4040"
    volumes:
      - delta:/storage
  delta-consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile-delta
    networks:
      - wikiflow-network
    ports:
      - "4041:4040"
    volumes:
      - delta:/storage
    depends_on:
      - "analytics-consumer"
networks:
  wikiflow-network:
    external:
      name: wikiflow-network
volumes:
  delta: